# The URL the site will be built for
base_url = "https://github.com/hellfireclub2020/bug-free-fishstick"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Use after-dark theme from the `themes` directory
theme = "after-dark"

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
output_dir = "docs"

# Taxonomies
taxonomies = [
    # You can enable/disable RSS
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
# Set the author of the site
author = "hfc2020"

# The menu items that will be displayed in the header
after_dark_menu = [
    { url = "$BASE_URL", name = "Home" },
    { url = "$BASE_URL/categories", name = "Categories" },
    { url = "$BASE_URL/tags", name = "Tags" },
    { url = "https://kagi.com", name = "Kagi" },
]

# The title of the site
after_dark_title = "Bug Free Fishstick"
